Repository microsoft/PowerStig, pull requests merged in 2019-02, with the labels that each got.

#273 Update PowerSTIG to parse the Windows 10 STIG V1R16
  CHANGELOG.md
  Module/Common/Function.RangeConversion.ps1
  Module/UserRightsAssignmentRule/Methods.ps1
  StigData/Archive/Windows.Client/U_Windows_10_STIG_V1R16_Manual-xccdf.xml
  StigData/Processed/Windows-10-Client-1.16.org.default.xml
  StigData/Processed/Windows-10-Client-1.16.xml
Labels: In Progress, enhancement

#272 Update PowerSTIG to parse the Windows Server 2012R2 DC V2R15 STIG
  CHANGELOG.md
  DSCResources/WindowsServer/WindowsServer.schema.psm1
  Module/PermissionRule/Methods.ps1
  StigData/Archive/Windows.Server.2012R2/U_Windows_2012_and_2012_R2_DC_STIG-xccdf.md
  StigData/Archive/Windows.Server.2012R2/U_Windows_2012_and_2012_R2_DC_STIG_V2R15_Manual-xccdf.xml
  StigData/Processed/Windows-2012R2-DC-2.15.org.default.xml
  StigData/Processed/Windows-2012R2-DC-2.15.xml
Labels: enhancement

#271 Update PowerSTIG to parse the SQL Server 2012 Database V1R18 STIG
  CHANGELOG.md
  DSCResources/Browser/Browser.schema.psm1
  DSCResources/FireFox/FireFox.schema.psm1
  DSCResources/SqlServer/SqlServer.schema.psm1
  DSCResources/WindowsClient/WindowsClient.schema.psm1
  DSCResources/WindowsDnsServer/WindowsDnsServer.schema.psm1
  DSCResources/WindowsServer/WindowsServer.schema.psm1
  StigData/Archive/SQL Server/U_MS_SQL_Server_2012_Database_STIG_V1R18_Manual-xccdf.xml
  StigData/Archive/Windows.Client/U_Windows_10_STIG_V1R16_Manual-xccdf.xml
  StigData/Archive/Windows.DNS/U_MS_Windows_2012_Server_DNS_STIG_V1R11_Manual-xccdf.xml
  StigData/Archive/Windows.DNS/U_MS_Windows_2012_Server_DNS_STIG_V1R7_Manual-xccdf.xml
  StigData/Archive/Windows.Server.2012R2/U_Windows_2012_and_2012_R2_DC_STIG_V2R12_Manual-xccdf.xml
  StigData/Archive/browser/U_Mozilla_FireFox_STIG_V4R24_Manual-xccdf.xml
  StigData/Processed/Mozilla-All-FireFox-4.21.xml
  StigData/Processed/SqlServer-2012-Database-1.18.org.default.xml
  StigData/Processed/SqlServer-2012-Database-1.18.xml
  StigData/Processed/SqlServer-2012-Instance-1.15.org.default.xml
  StigData/Processed/SqlServer-2012-Instance-1.15.xml
  StigData/Processed/WIndows-2012R2-DNS-1.7.org.default.xml
  StigData/Processed/WIndows-2012R2-DNS-1.9.org.default.xml
  StigData/Processed/Windows-10-Client-1.14.org.default.xml
  StigData/Processed/Windows-10-Client-1.14.xml
  StigData/Processed/Windows-2012R2-DC-2.12.org.default.xml
  StigData/Processed/Windows-2012R2-DC-2.12.xml
  StigData/Processed/Windows-2012R2-DC-2.13.org.default.xml
  StigData/Processed/Windows-2012R2-DC-2.13.xml
  StigData/Processed/Windows-2012R2-DNS-1.7.xml
  StigData/Processed/Windows-2012R2-DNS-1.9.xml
  StigData/Processed/Windows-2012R2-MS-2.12.org.default.xml
  StigData/Processed/Windows-2012R2-MS-2.12.xml
  StigData/Processed/Windows-All-IE11-1.13.org.default.xml
  StigData/Processed/Windows-All-IE11-1.13.xml
  Tests/Integration/Convert.Main.Integration.tests.ps1
  Tests/Unit/Module/STIG.tests.ps1
Labels: enhancement

#279 Updated UserRightsAssignment composite to leverage the Force parameter.
  CHANGELOG.md
  DSCResources/Resources/windows.UserRightsAssignment.ps1
Labels: bug

#281 fixed HKCU cAdministrativeTemplateSetting composite issue.
  CHANGELOG.md
  DSCResources/Resources/windows.cAdministrativeTemplateSetting.ps1
Labels: bug

#288 Fixes #284
  CHANGELOG.md
  Module/Rule.Registry/Convert/Methods.ps1
  StigData/Archive/Windows.Client/U_Windows_10_STIG_V1R14_Manual-xccdf.log
  StigData/Archive/Windows.Client/U_Windows_10_STIG_V1R15_Manual-xccdf.log
  StigData/Archive/Windows.Client/U_Windows_10_STIG_V1R16_Manual-xccdf.log
  StigData/Processed/WindowsClient-10-1.14.org.default.xml
  StigData/Processed/WindowsClient-10-1.14.xml
  StigData/Processed/WindowsClient-10-1.15.xml
  StigData/Processed/WindowsClient-10-1.16.org.default.xml
  StigData/Processed/WindowsClient-10-1.16.xml
  Tests/Unit/Module/RegistryRule.tests.ps1
Labels: bug

#291 Duplicate and/or ExclusionRuleList Conversion Error -> Fixes #289
  CHANGELOG.md
  Module/Rule.Document/Convert/DocumentRule.Convert.psm1
  Module/Rule.Document/DocumentRule.psm1
  Module/STIG/Convert/Functions.XccdfXml.ps1
Labels: bug

#292 IIS Server STIG V-76731 fails to properly set STIG guidance because rule is not split -> Fixes #290
  CHANGELOG.md
  Module/Rule.WebConfigurationProperty/Convert/Data.ps1
  Module/Rule.WebConfigurationProperty/Convert/Methods.ps1
  StigData/Archive/Web Server/U_IIS_8-5_Server_STIG_V1R3_Manual-xccdf.log
  StigData/Processed/IISServer-8.5-1.3.org.default.xml
  StigData/Processed/IISServer-8.5-1.3.xml
  StigData/Processed/IISServer-8.5-1.5.org.default.xml
  StigData/Processed/IISServer-8.5-1.5.xml
  StigData/Processed/IISServer-8.5-1.6.org.default.xml
  StigData/Processed/IISServer-8.5-1.6.xml
  Tests/Integration/WebConfigurationPropertyRule.Integration.tests.ps1
Labels: bug

#321 Update PowerSTIG to Utilize LogTargetW3C parameter in xWebAdministration 2.5.0.0
  CHANGELOG.md
  DSCResources/IisServer/IisServer.schema.psm1
  DSCResources/IisSite/IisSite.schema.psm1
  DSCResources/Resources/windows.xIisLogging.ps1
  DSCResources/Resources/windows.xWebSite.ps1
  PowerStig.psd1
Labels: enhancement

#333 Dav bowman#319
  CHANGELOG.md
  StigData/Archive/Windows.Firewall/U_Windows_Firewall_STIG_V1R7_Manual-xccdf.xml
  StigData/Processed/WindowsFirewall-All-1.7.org.default.xml
  StigData/Processed/WindowsFirewall-All-1.7.xml
Labels: In Progress, enhancement

#332 Fix for #331 - PermissionRule.Convert CheckContent Match Parser Update
  CHANGELOG.md
  Module/Rule.Permission/Convert/PermissionRule.Convert.psm1
  StigData/Archive/Windows.Server.2012R2/U_Windows_2012_and_2012_R2_DC_STIG_V2R13_Manual-xccdf.log
  StigData/Archive/Windows.Server.2012R2/U_Windows_2012_and_2012_R2_DC_STIG_V2R14_Manual-xccdf.log
  StigData/Archive/Windows.Server.2012R2/U_Windows_2012_and_2012_R2_DC_STIG_V2R15_Manual-xccdf.log
Labels: bug
